# fly.toml app configuration file generated for tgava on 2023-06-22T22:42:00+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "avabot"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
